function enc(){
var str =  prompt("Insert the text to encrypt");
var str2 = str.replaceAll('a', 'º')
              .replaceAll('b', 'ª')
				      .replaceAll('c', '!')
				      .replaceAll('d', '|')
				      .replaceAll('e', '"')
		    		  .replaceAll('f', '@')
				      .replaceAll('g', '·')
    				  .replaceAll('h', '#')
		    		  .replaceAll('i', '$')
	    			  .replaceAll('j', '~')
	    			  .replaceAll('k', '%')
	    			  .replaceAll('l', '&')
	    			  .replaceAll('m', '¬')
	    			  .replaceAll('n', '/')
	    			  .replaceAll('o', '(')
	    			  .replaceAll('p', ')')
	    			  .replaceAll('q', '=')
	    			  .replaceAll('r', '?')
	    			  .replaceAll('s', '¿')
    				  .replaceAll('t', '¡')
    				  .replaceAll('u', '[')
    				  .replaceAll('v', ']')
    				  .replaceAll('w', '+')
    				  .replaceAll('x', '*')
    				  .replaceAll('y', '{')
    				  .replaceAll('z', '}')
				  //Mayus
				  .replaceAll('A', 'º')
          .replaceAll('B', 'ª')
				  .replaceAll('C', '!')
				  .replaceAll('D', '|')
				  .replaceAll('E', '"')
				  .replaceAll('F', '@')
				  .replaceAll('G', '·')
				  .replaceAll('H', '#')
				  .replaceAll('I', '$')
				  .replaceAll('J', '~')
				  .replaceAll('K', '%')
				  .replaceAll('L', '&')
				  .replaceAll('M', '¬')
				  .replaceAll('N', '/')
				  .replaceAll('O', '(')
				  .replaceAll('P', ')')
				  .replaceAll('Q', '=')
				  .replaceAll('R', '?')
				  .replaceAll('S', '¿')
				  .replaceAll('T', '¡')
				  .replaceAll('U', '[')
				  .replaceAll('V', ']')
				  .replaceAll('W', '+')
				  .replaceAll('X', '*')
				  .replaceAll('Y', '{')
				  .replaceAll('Z', '}')
alert(str2)
}
function dec(){
var str =  prompt("Insert text to decrypt:");
var str2 = str.replaceAll('º', 'a')
              .replaceAll('ª', 'b')
				      .replaceAll('!', 'c')
    				  .replaceAll('|', 'd')
    				  .replaceAll('"', 'e')
    				  .replaceAll('@', 'f')
	    			  .replaceAll('·', 'g')
	    			  .replaceAll('#', 'h')
		    		  .replaceAll('$', 'i')
				      .replaceAll('~', 'j')
	    			  .replaceAll('%', 'k')
	    			  .replaceAll('&', 'l')
	    			  .replaceAll('¬', 'm')
	    			  .replaceAll('/', 'n')
	    			  .replaceAll('(', 'o')
	    			  .replaceAll(')', 'p')
	    			  .replaceAll('=', 'q')
	    			  .replaceAll('?', 'r')
	    			  .replaceAll('¿', 's')
	    			  .replaceAll('¡', 't')
		    		  .replaceAll('[', 'u')
			    	  .replaceAll(']', 'v')
	    			  .replaceAll('+', 'w')
	    			  .replaceAll('*', 'x')
	    			  .replaceAll('{', 'y')
	    			  .replaceAll('}', 'z')

alert(str2)}
